version: '3'

services:
  appdlserver:
    image: appdlserver
    build:
      context: ./appdlserver
      dockerfile: appdlserver/Dockerfile
    env_file: .env.example
    ports:
      - 3000:3000

  shining:
    image: shining
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
