version: "3"

services:
  appdlserver:
    container_name: appdlserver
    image: appdlserver
    restart: unless-stopped
    build:
      context: ./appdlserver
      dockerfile: appdlserver/Dockerfile
    environment:
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "appdlserver"
      PG_PW: "abc123654"
      PG_DBNAME: "appdlserver"
      PORT: "3000"
      BASE_URL: "https://xxx.com.cn"
      OSS_END_POINT: "oss-cn-hangzhou.aliyuncs.com"
      OSS_ACCESS_KEY_ID: "xxxxxxx"
      OSS_ACCESS_KEY_SECRET: "xxxxxxxx"
      OSS_BUCKET: "apksave"
    ports:
      - 3000:3000
    networks:
      - shining
    depends_on:
      - postgres

  shining:
    container_name: shining
    image: shining
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - default.conf:/etc/nginx/conf.d/default.conf
      # 配置ssl证书,请务必配置正确，否则IOS无法正常安装
      # - xxx.crt:/etc/nginx/ssl/bundle.crt
      # - bundle.key:/etc/nginx/ssl/bundle.key
    ports:
      - 80:80
      - 443:443
    networks:
      - shining
    depends_on:
      - appdlserver

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /home/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: abc123654
      POSTGRES_DB: appdlserver
      POSTGRES_USER: appdlserver
    networks:
      - shining

networks:
  shining:
